include_defs('//bucklets/maven_jar.bucklet')

VER = '2.13.4'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = '160d75e686f57d9f20748d3396a77a0f0a6a90a4',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)
